#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: R
# autospec version: v2
# autospec commit: e661f3a
#
Name     : R-webutils
Version  : 1.2.0
Release  : 41
URL      : https://cran.r-project.org/src/contrib/webutils_1.2.0.tar.gz
Source0  : https://cran.r-project.org/src/contrib/webutils_1.2.0.tar.gz
Summary  : Utility Functions for Developing Web Applications
Group    : Development/Tools
License  : MIT
Requires: R-webutils-lib = %{version}-%{release}
Requires: R-curl
Requires: R-jsonlite
BuildRequires : R-curl
BuildRequires : R-httpuv
BuildRequires : R-jsonlite
BuildRequires : buildreq-R
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
or application/x-www-form-urlencoded format. Includes example of hosting
    and parsing html form data in R using either 'httpuv' or 'Rhttpd'.

%package lib
Summary: lib components for the R-webutils package.
Group: Libraries

%description lib
lib components for the R-webutils package.


%prep
%setup -q -n webutils
pushd ..
cp -a webutils buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1700989861

%install
export SOURCE_DATE_EPOCH=1700989861
rm -rf %{buildroot}
LANG=C.UTF-8
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -flto -fno-semantic-interposition "
FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -flto -fno-semantic-interposition "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -flto -fno-semantic-interposition "
AR=gcc-ar
RANLIB=gcc-ranlib
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS  -Wl,-z -Wl,relro"
mkdir -p %{buildroot}/usr/lib64/R/library

mkdir -p ~/.R
mkdir -p ~/.stash
echo "CFLAGS = $CFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper" > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v3 -ftree-vectorize -mno-vzeroupper " >> ~/.R/Makevars
R CMD INSTALL --install-tests --use-LTO --built-timestamp=${SOURCE_DATE_EPOCH} --data-compress=none --compress=none --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx2 ; mv $i.avx2 ~/.stash/; done
echo "CFLAGS = $CFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -march=x86-64-v4 -ftree-vectorize  -mno-vzeroupper -mprefer-vector-width=512 " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -march=x86-64-v4 -ftree-vectorize -mno-vzeroupper -mprefer-vector-width=512  " >> ~/.R/Makevars
R CMD INSTALL --preclean --install-tests --use-LTO --no-test-load --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
for i in `find %{buildroot}/usr/lib64/R/ -name "*.so"`; do mv $i $i.avx512 ; mv $i.avx512 ~/.stash/; done
echo "CFLAGS = $CFLAGS -ftree-vectorize " > ~/.R/Makevars
echo "FFLAGS = $FFLAGS -ftree-vectorize " >> ~/.R/Makevars
echo "CXXFLAGS = $CXXFLAGS -ftree-vectorize " >> ~/.R/Makevars
R CMD INSTALL --preclean --use-LTO --install-tests --data-compress=none --compress=none --built-timestamp=${SOURCE_DATE_EPOCH} --build  -l %{buildroot}/usr/lib64/R/library .
cp ~/.stash/* %{buildroot}/usr/lib64/R/library/*/libs/ || :
%{__rm} -rf %{buildroot}%{_datadir}/R/library/R.css
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export _R_CHECK_FORCE_SUGGESTS_=false
R CMD check --no-manual --no-examples --no-codoc . || :

/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)
/usr/lib64/R/library/webutils/DESCRIPTION
/usr/lib64/R/library/webutils/INDEX
/usr/lib64/R/library/webutils/LICENSE
/usr/lib64/R/library/webutils/Meta/Rd.rds
/usr/lib64/R/library/webutils/Meta/features.rds
/usr/lib64/R/library/webutils/Meta/hsearch.rds
/usr/lib64/R/library/webutils/Meta/links.rds
/usr/lib64/R/library/webutils/Meta/nsInfo.rds
/usr/lib64/R/library/webutils/Meta/package.rds
/usr/lib64/R/library/webutils/NAMESPACE
/usr/lib64/R/library/webutils/NEWS
/usr/lib64/R/library/webutils/R/webutils
/usr/lib64/R/library/webutils/R/webutils.rdb
/usr/lib64/R/library/webutils/R/webutils.rdx
/usr/lib64/R/library/webutils/help/AnIndex
/usr/lib64/R/library/webutils/help/aliases.rds
/usr/lib64/R/library/webutils/help/paths.rds
/usr/lib64/R/library/webutils/help/webutils.rdb
/usr/lib64/R/library/webutils/help/webutils.rdx
/usr/lib64/R/library/webutils/html/00Index.html
/usr/lib64/R/library/webutils/html/R.css
/usr/lib64/R/library/webutils/testpage.html
/usr/lib64/R/library/webutils/tests/testthat.R
/usr/lib64/R/library/webutils/tests/testthat/description.orig
/usr/lib64/R/library/webutils/tests/testthat/iris.orig
/usr/lib64/R/library/webutils/tests/testthat/logo.orig
/usr/lib64/R/library/webutils/tests/testthat/posttypes
/usr/lib64/R/library/webutils/tests/testthat/test-echo.R
/usr/lib64/R/library/webutils/tests/testthat/test-encoding.R
/usr/lib64/R/library/webutils/tests/testthat/test-parse.R

%files lib
%defattr(-,root,root,-)
/usr/lib64/R/library/webutils/libs/webutils.so
/usr/lib64/R/library/webutils/libs/webutils.so.avx2
/usr/lib64/R/library/webutils/libs/webutils.so.avx512
